### PR TITLE
Merge release 1.0.0

### PR DESCRIPTION
**Pull request by mattc-cogapp**
Contains one single story: [#91013274 - Cookie policy banner/pop-up](https://www.pivotaltracker.com/story/show/91013274)

### CODE REVIEW

**Comment by mattc-cogapp** [comment]
@samueljmurray could you take a look at this in the absence of any Festival team members in the office? Cheers!

**Comment by mattc-cogapp** [comment]
Sorry @djvern , didn't realise Sam was off today! Could you take a look at this please? Cheers!

**Comment by djvern** [comment]
Yep no problem, looking now....

**Comment by djvern** [comment]
@mattc-cogapp what's the best way to test this? Can I add it to the webwewant site and run the tests from there?

**Comment by mattc-cogapp** [comment]
It's already added on http://webwewant.mattc.sc.cogapp.com, so that's the best place to look.

There's also unit tests that you can find out about in the README.txt if you need to.

**Comment by djvern** [comment]
@mattc-cogapp can I get you on hangouts as I have a few questions?

**Pull request merged**
